# Generated by Django 2.2 on 2021-09-02 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Specialization',
            field=models.CharField(default=datetime.datetime(2021, 9, 2, 15, 8, 13, 729826, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
